import fs from "fs";
import { svgPathBbox } from "svg-path-bbox";

const svg = fs.readFileSync("branding/K2Logo.svg", "utf8");
const paths = [...svg.matchAll(/<path class="st16" d="([^"]+)"/g)].map((m) => m[1]);
console.log("paths", paths.length);

let minX = Infinity,
  minY = Infinity,
  maxX = -Infinity,
  maxY = -Infinity;

for (const d of paths) {
  const box = svgPathBbox(d);
  minX = Math.min(minX, box[0]);
  minY = Math.min(minY, box[1]);
  maxX = Math.max(maxX, box[2]);
  maxY = Math.max(maxY, box[3]);
}

// Curves on the “2” can extend past the computed bbox — extra room on the right.
const pad = { top: 4, right: 28, bottom: 4, left: 4 };
const vb = [
  minX - pad.left,
  minY - pad.top,
  maxX - minX + pad.left + pad.right,
  maxY - minY + pad.top + pad.bottom,
].map((n) => Math.round(n * 100) / 100);

console.log({ minX, minY, maxX, maxY, viewBox: vb.join(" ") });

const out = `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb.join(" ")}" fill="currentColor">
${paths.map((d) => `  <path d="${d}"/>`).join("\n")}
</svg>
`;
fs.writeFileSync("public/k2-logo.svg", out);

const tsPaths = paths.map((d) => JSON.stringify(d)).join(",\n  ");
const component = `// Generated by scripts/extract-logo.mjs — do not edit paths by hand.
import { cn } from "@/lib/utils";

const LOGO_PATHS = [
  ${tsPaths},
] as const;

const VIEWBOX = "${vb.join(" ")}";

type K2LogoProps = {
  className?: string;
  title?: string;
};

/** Inline K2 wordmark — scales crisply at any size. */
export function K2Logo({ className, title }: K2LogoProps) {
  return (
    <span
      className={cn(
        "flex h-9 shrink-0 aspect-[1181/788] items-center text-pitch",
        className,
      )}
      role={title ? "img" : undefined}
      aria-label={title}
      aria-hidden={title ? undefined : true}
    >
      <svg
        xmlns="http://www.w3.org/2000/svg"
        viewBox={VIEWBOX}
        fill="currentColor"
        className="size-full"
      >
        {LOGO_PATHS.map((d, i) => (
          <path key={i} d={d} />
        ))}
      </svg>
    </span>
  );
}
`;
fs.writeFileSync("src/components/site/K2Logo.tsx", component);
console.log("wrote public/k2-logo.svg and src/components/site/K2Logo.tsx");
